# Generated by Django 3.1.7 on 2021-03-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidfood',
            name='death_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='covidfood',
            name='fs_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='covidfood',
            name='pr_fs_rati',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
